
apiVersion: v1
kind: Service
metadata:
  name: pds-ui
  namespace: pds-516
  labels:
    app: pds-ui
    team: platform
    network-code: CN580004
    version: "v1.0"
    managed-by: backstage
  annotations:
    description: "Service for pds-ui"
spec:
  type: ClusterIP
  selector:
    app: pds-ui
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
