
apiVersion: ibm.idp.io/v1alpha1
kind: IBMDatabase
metadata:
  name: fm500-postgres
  namespace: fm500
  labels:
    network-code: cn580005
    team: platform
    managed-by: backstage
spec:
  parameters:
    dbName: fm500-postgres
    dbType: postgresql
    region: us-south
    memoryMb: 8192
    diskMb: 20480
