---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-pds-kafka
  namespace: dev
  labels:
    app: kafka-pds-kafka
    team: platform
    managed-by: backstage
  annotations:
    description: "test"
spec:
  kafka:
    version: 3.7.1
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
      log.retention.hours: 168
      log.segment.bytes: 1073741824
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
      periodSeconds: 20
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
      periodSeconds: 20
      failureThreshold: 3
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      class: standard-rwo
    template:
      pod:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - kafka-pds-kafka
                  topologyKey: kubernetes.io/hostname
        metadata:
          labels:
            app: kafka-pds-kafka
            team: platform
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
      class: standard-rwo
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "300m"
        memory: "512Mi"
    template:
      pod:
        metadata:
          labels:
            app: kafka-pds-kafka
            team: platform
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    userOperator:
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
    template:
      topicOperatorContainer:
        env:
          - name: STRIMZI_KUBERNETES_VERSION
            value: "major=1,minor=31"
        livenessProbe:
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
      userOperatorContainer:
        env:
          - name: STRIMZI_KUBERNETES_VERSION
            value: "major=1,minor=31"
        livenessProbe:
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 20
          failureThreshold: 3
