
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pds-alertevent
  namespace: dev
  labels:
    strimzi.io/cluster: pds-kafka
    team: platform
    managed-by: backstage
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
    segment.bytes: "1073741824"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pds-trackline
  namespace: dev
  labels:
    strimzi.io/cluster: pds-kafka
    team: platform
    managed-by: backstage
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: "604800000"
    segment.bytes: "1073741824"
