
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pds-{{ topic.topicName }}
  namespace: dev
  labels:
    strimzi.io/cluster: pds-kafka
    team: platform
    managed-by: backstage
spec:
  partitions: {{ topic.partitions }}
  replicas: {{ topic.replicationFactor | default(1) }}
  config:
    retention.ms: "{{ (topic.retentionHours | default(168)) * 3600000 }}"
    segment.bytes: "1073741824"
