---
apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: pds-509-db
  namespace: dev
  labels:
    app: cockroachdb-pds-509-db
    team: platform
    managed-by: backstage
spec:
  connection:
    postgres:
      host:
        value: cockroachdb-pds-509-db.dev.svc.cluster.local
      port:
        value: "26257"
      user:
        value: root
      password:
        value: ""
      dbname:
        value: alertevent
      sslmode:
        value: disable
