---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pds-512-namespace
  description: "test"
  tags:
    - namespace
    - environment
    - idp-managed
    - network-code-cn580005
  links:
    - title: GitOps Source
      url: https://github.com/devopssimplify/idp-poc-gitops/blob/main/cluster/namespace-pds-512.yaml
      icon: github
spec:
  type: environment
  lifecycle: production
  owner: group:default/backend
  system: CN580005
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: CN580005
  description: "Network code CN580005 — all resources billed to this cost center"
  tags:
    - network-code
    - idp-managed
spec:
  owner: group:default/backend
