apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: config-connector
  annotations:
    cnrm.cloud.google.com/project-id: "project-7d27fad9-61bb-42c4-b2e"  # replace this

---
apiVersion: v1
kind: Namespace
metadata:
  name: pds-500
---

apiVersion: v1
kind: Namespace
metadata:
  name: pds-501
